### ISSUE TITLE
Editing files for a mod

### ISSUE THREAD

**Issue by Saturate** [kk49/deca#99] opened 2020-03-31 16:11 UTC
Hi there,

I'm trying to change some settings in `playersettings.playersettingsc` and while I can export it and change it, it seems like the modding part of the deca can't export it as txt so that I can change it. So how can I change values in this ADF format? Do I need to boot up my HEX editor or is there another way I'm not seeing?

**Comment by kk49** [comment] 2020-03-31 18:15
Currently you do need to use a hex editor. Some people have had some luck with some of the JustCause tools, but I haven't used them. The discord has a set of people who are modding the game it's a good place to get some info and support. ADFB files require using an offset to find the right location to edit. There is a youtube video about it (with an old offset)

https://www.youtube.com/watch?v=2nH-TERH51g

The discord
https://discord.gg/x5AuPj7

**Comment by Saturate** [comment] 2020-04-01 10:07
Thanks :-) that helps me.

**Comment by kk49** [comment] 2020-04-01 14:37
You're welcome! 

This is another vote for ADF serialization support so marking as a duplicate of #18

**Closed by kk49** 2020-04-01 14:37 UTC
